### ISSUE TITLE
Publish `master` version

### ISSUE THREAD

**Issue by twolfson** [kriskowal/url2#6]
We have received an issue on `gulp.spritesmith` about being unable to commit `node_modules` to `git` due to a bad dependency in `url`.

https://github.com/twolfson/gulp.spritesmith/issues/34

This seems to have been patched via #5 but hasn't been published to `npm`. Can we publish the version on `master`?

**Comment by kriskowal** [comment]
Tests fail in Phantom on master. See https://github.com/defunctzombie/node-url/pull/16

**Comment by twolfson** [comment]
Cool, I will subscribe to the PR. Thanks!

**Comment by twolfson** [comment]
The PR seems to have landed, can we update to it and publish `master`?

**Comment by twolfson** [comment]
Any progress on this?

**Comment by kriskowal** [comment]
Published 1.0.4 from master. Apologies for the delay. Would be glad to add
collaborators with npm and git accounts.

**Comment by twolfson** [comment]
No worries. I am happy to become a contributor. `twolfson` on GitHub and `twolfson` on `npm`. I am going to close this issue as closed =)
